// <auto-generated />
using System;
using SisMedico.InfraData.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SisMedico.InfraData.Migrations;

[DbContext(typeof(ITDeveloperDbContext))]
[Migration("20210623195743_RenameNovoProntuarioNotificacaoToTriagem")]
partial class RenameNovoProntuarioNotificacaoToTriagem
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.7")
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        modelBuilder.Entity("SisMedico.Domain.Entities.Author", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("EmailAddress")
                    .HasMaxLength(255)
                    .HasColumnType("varchar(255)")
                    .HasColumnName("EmailAddress");

                b.Property<string>("LastName")
                    .HasMaxLength(70)
                    .HasColumnType("varchar(70)")
                    .HasColumnName("LastName");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("Name");

                b.Property<string>("WebSite")
                    .HasMaxLength(255)
                    .HasColumnType("varchar(255)")
                    .HasColumnName("WebSite");

                b.HasKey("Id");

                b.ToTable("Author");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.ChamadaMedica", b =>
            {
                b.Property<int>("ChamadaMedicoId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("DataChamada")
                    .HasColumnType("datetime2");

                b.Property<string>("Leito")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("varchar(10)");

                b.Property<string>("Medico")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("varchar(80)");

                b.Property<string>("Mensagem")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.HasKey("ChamadaMedicoId");

                b.ToTable("ChamadaMedica");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Cid", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("CidInternalId")
                    .HasColumnType("int")
                    .HasColumnName("CidInternalId");

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(6)
                    .HasColumnType("varchar(6)")
                    .HasColumnName("Codigo");

                b.Property<string>("Diagnostico")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)")
                    .HasColumnName("Diagnostico");

                b.HasKey("Id");

                b.ToTable("Cid");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.EstadoPaciente", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("varchar(20)")
                    .HasColumnName("Descricao");

                b.HasKey("Id");

                b.ToTable("EstadoPaciente");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Generico", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Codigo")
                    .HasColumnType("int");

                b.Property<string>("Nome")
                    .HasColumnType("varchar(90)");

                b.HasKey("Id");

                b.ToTable("Generico");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.MasterDetails.Team", b =>
            {
                b.Property<int>("TeamID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Description")
                    .HasColumnType("varchar(90)");

                b.Property<string>("Name")
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.HasKey("TeamID");

                b.ToTable("Teams");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.MasterDetails.TeamMember", b =>
            {
                b.Property<int>("TeamMemberID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Email")
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<string>("Name")
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<int>("TeamID")
                    .HasColumnType("int");

                b.HasKey("TeamMemberID");

                b.HasIndex("TeamID");

                b.ToTable("TeamMembers");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Medicamento", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Codigo")
                    .HasColumnType("int");

                b.Property<int>("CodigoGenerico")
                    .HasColumnType("int");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)")
                    .HasColumnName("Descricao");

                b.Property<string>("Generico")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)")
                    .HasColumnName("Generico");

                b.HasKey("Id");

                b.ToTable("Medicamento");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Mural", b =>
            {
                b.Property<int>("MuralId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Autor")
                    .HasColumnType("varchar(90)");

                b.Property<string>("Aviso")
                    .HasColumnType("varchar(90)");

                b.Property<DateTime>("Data")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .HasColumnType("varchar(90)");

                b.Property<string>("Titulo")
                    .HasColumnType("varchar(90)");

                b.HasKey("MuralId");

                b.ToTable("Mural");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Paciente", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("Ativo")
                    .HasColumnType("bit");

                b.Property<string>("Cpf")
                    .HasMaxLength(11)
                    .HasColumnType("varchar(11)")
                    .HasColumnName("Cpf")
                    .IsFixedLength(true);

                b.Property<DateTime>("DataInternacao")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("DataNascimento")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .HasColumnType("varchar(150)")
                    .HasColumnName("Email");

                b.Property<Guid>("EstadoPacienteId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Motivo")
                    .HasColumnType("varchar(90)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("varchar(80)")
                    .HasColumnName("Nome");

                b.Property<string>("Rg")
                    .HasMaxLength(15)
                    .HasColumnType("varchar(15)")
                    .HasColumnName("Rg");

                b.Property<DateTime>("RgDataEmissao")
                    .HasColumnType("datetime2");

                b.Property<string>("RgOrgao")
                    .HasColumnType("varchar(10)")
                    .HasColumnName("RgOrgao");

                b.Property<int>("Sexo")
                    .HasColumnType("int");

                b.Property<int>("TipoDeCliente")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("EstadoPacienteId");

                b.ToTable("Paciente");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.PacienteTeste", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("adate")
                    .HasColumnType("datetime2");

                b.Property<decimal>("balance")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("ipAddress")
                    .HasColumnType("varchar(90)");

                b.Property<string>("package")
                    .HasColumnType("varchar(90)");

                b.Property<int>("port")
                    .HasColumnType("int");

                b.Property<string>("status")
                    .HasColumnType("varchar(90)");

                b.Property<string>("user")
                    .HasColumnType("varchar(90)");

                b.HasKey("Id");

                b.ToTable("PacienteTestes");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Tags", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("AuthorId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Note")
                    .HasColumnType("nvarchar(MAX)")
                    .HasColumnName("Note");

                b.Property<string>("SourceAt")
                    .IsRequired()
                    .HasColumnType("nvarchar(MAX)")
                    .HasColumnName("SourceAt");

                b.Property<string>("Tag")
                    .IsRequired()
                    .HasMaxLength(90)
                    .HasColumnType("varchar(90)")
                    .HasColumnName("Tag");

                b.HasKey("Id");

                b.HasIndex("AuthorId");

                b.ToTable("Tags");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Telefone", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("AuthorId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Ddd")
                    .HasColumnType("varchar(90)");

                b.Property<string>("Numero")
                    .HasColumnType("varchar(90)");

                b.Property<int>("TipoTelefone")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("AuthorId");

                b.ToTable("Telefone");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Triagem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CodigoPaciente")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("DataNotificacao")
                    .HasColumnType("datetime2");

                b.Property<string>("Mensagem")
                    .IsRequired()
                    .HasMaxLength(90)
                    .HasColumnType("varchar(90)");

                b.Property<string>("NomePaciente")
                    .IsRequired()
                    .HasMaxLength(90)
                    .HasColumnType("varchar(90)");

                b.HasKey("Id");

                b.ToTable("Triagem");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Author", b =>
            {
                b.OwnsOne("SisMedico.Domain.ValueObjects.RedesSociais", "RedesSociais", b1 =>
                    {
                        b1.Property<Guid>("AuthorId")
                            .HasColumnType("uniqueidentifier");

                        b1.Property<string>("Facebook")
                            .HasMaxLength(400)
                            .HasColumnType("varchar(400)")
                            .HasColumnName("Facebook");

                        b1.Property<string>("Linkedin")
                            .HasMaxLength(400)
                            .HasColumnType("varchar(400)")
                            .HasColumnName("Linkedin");

                        b1.Property<string>("Twitter")
                            .HasMaxLength(400)
                            .HasColumnType("varchar(400)")
                            .HasColumnName("Twitter");

                        b1.HasKey("AuthorId");

                        b1.ToTable("Author");

                        b1.WithOwner()
                            .HasForeignKey("AuthorId");
                    });

                b.Navigation("RedesSociais");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.MasterDetails.TeamMember", b =>
            {
                b.HasOne("SisMedico.Domain.Entities.MasterDetails.Team", null)
                    .WithMany("Members")
                    .HasForeignKey("TeamID")
                    .OnDelete(DeleteBehavior.ClientNoAction)
                    .IsRequired();
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Paciente", b =>
            {
                b.HasOne("SisMedico.Domain.Entities.EstadoPaciente", "EstadoPaciente")
                    .WithMany("Paciente")
                    .HasForeignKey("EstadoPacienteId")
                    .OnDelete(DeleteBehavior.ClientNoAction)
                    .IsRequired();

                b.Navigation("EstadoPaciente");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Tags", b =>
            {
                b.HasOne("SisMedico.Domain.Entities.Author", "Author")
                    .WithMany("Tags")
                    .HasForeignKey("AuthorId")
                    .OnDelete(DeleteBehavior.ClientNoAction)
                    .IsRequired();

                b.Navigation("Author");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Telefone", b =>
            {
                b.HasOne("SisMedico.Domain.Entities.Author", "Author")
                    .WithMany("Telefone")
                    .HasForeignKey("AuthorId")
                    .OnDelete(DeleteBehavior.ClientNoAction)
                    .IsRequired();

                b.Navigation("Author");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.Author", b =>
            {
                b.Navigation("Tags");

                b.Navigation("Telefone");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.EstadoPaciente", b =>
            {
                b.Navigation("Paciente");
            });

        modelBuilder.Entity("SisMedico.Domain.Entities.MasterDetails.Team", b =>
            {
                b.Navigation("Members");
            });
#pragma warning restore 612, 618
    }
}
